[package]
name = "dji-log-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Library for parsing DJI txt logs"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
aes.workspace = true
base64.workspace = true
binrw.workspace = true
cbc.workspace = true
chrono = { workspace = true, features = ["serde"] }
crc64.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror.workspace = true
ureq = { workspace = true, features = ["json"] }
log = "0.4"
geojson = "0.24.0"
once_cell = "1.8.0"

[lib]
name = "dji_log_parser"
crate-type = ["staticlib", "rlib"]